from __future__ import annotations

import os


ANALYSIS_GENERATION_MODE = os.getenv("ANALYSIS_GENERATION_MODE", "template")
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openai")

PROFIT_ADVANCE_REFERENCE = os.getenv("PROFIT_ADVANCE_REFERENCE", "mai/2026")
PROFIT_ADVANCE_PAYMENT = os.getenv("PROFIT_ADVANCE_PAYMENT", "Julho / 2026")
PROFIT_ADVANCE_MONTHLY_RESULT = float(os.getenv("PROFIT_ADVANCE_MONTHLY_RESULT", "792184.77"))
PROFIT_ADVANCE_ADJUSTMENT_PCT = float(os.getenv("PROFIT_ADVANCE_ADJUSTMENT_PCT", "15.0"))
PROFIT_ADVANCE_TOTAL_ADJUSTMENT = float(os.getenv("PROFIT_ADVANCE_TOTAL_ADJUSTMENT", "118827.72"))
PROFIT_ADVANCE_TOTAL_QUOTAS = float(os.getenv("PROFIT_ADVANCE_TOTAL_QUOTAS", "31681.81"))
PROFIT_ADVANCE_ADJUSTMENT_PER_QUOTA = float(os.getenv("PROFIT_ADVANCE_ADJUSTMENT_PER_QUOTA", "3.7507"))
